### PR TITLE
src: Make thread safe (see #3)

### PR DESCRIPTION
**Pull request by jwerle**
See #3

### CODE REVIEW

**Comment by jwerle** [comment]
:pray:

**Comment by jwerle** [comment]
bump :pray:

**Comment by stephenmathieson** [comment]
My bad, missed this. Want me to just transfer this repo to `clibs/`? I'm not using it for anything these days and don't know if I'll have time to maintain it.

**Comment by jwerle** [comment]
Yeah that'd be great ! 🙏🤙

**Comment by stephenmathieson** [comment]
I tried and got an error saying the repo already exists 🙃

**Comment by stephenmathieson** [comment]
Added you to the repo. LMK if there are any others you want access to (or repos that I should just transfer to clibs)

**Comment by jwerle** [comment]
Oops yeah there is a fork there 😂 I'll remove it so we can transfer this one

**Comment by jwerle** [comment]
okay done, sorry that took forever

**Pull request merged**
